spring:
  application:
    name: garage
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/garage_dev
    jdbc-url: jdbc:postgresql://localhost:5432/garage_dev
    username: postgres
    password: garage123
    hikari:
      pool-name: appdbpool
      minimum-idle: 10
      maximum-pool-size: 50
      keepalive-time: 300000
      max-lifetime: 300000
      connection-timeout: 60000
      validation-timeout: 30000
      leak-detection-threshold: 0
      initialization-fail-timeout: 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
    hibernate:
      ddl-auto: none
      default_schema:
      enable_lazy_load_no_trans: true
      use-new-id-generator-mappings: false
      order_inserts: true
      order_updates: true
      jdbc.batch_size: 100
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


app:
  cors:
    allowed-origins: "http:localhost:4000"
  jwt:
    secret: "4WadB8IxnpkmgqLdmWChE4+4b3AUNzXpOHosjGzHCNI="
    expiration-ms: 36000
    refresh-token:
      expiration-ms: 36000